# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

droplassoC <- function(x, y, family, keep_prob, lambda, binit, gamma0, n_passes, minibatch_size) {
    .Call(`_droplasso_droplassoC`, x, y, family, keep_prob, lambda, binit, gamma0, n_passes, minibatch_size)
}

